### ISSUE TITLE
Citing section mostly missing

### ISSUE THREAD

**Issue by malteos** [allenai/s2orc#10]
I quickly checked on a sample of 35,414 papers from the dataset and none has the `section` set in `paper.grobid_parse.body_text`. Is it just bad luck or is the section information missing for most papers?

**Comment by kyleclo** [comment]
I'll look into this ASAP, thanks for bringing attention

**Comment by kyleclo** [comment]
@malteos Thanks for drawing attention to this.  It's been fixed in the most recent release `20200705v1`.  Here's a screenshot of `grep '"section":'`

![image](https://user-images.githubusercontent.com/13603748/86875424-51038000-c097-11ea-9737-f7edc0f723ee.png)

**Comment by malteos** [comment]
Awesome! Thanks for your work
