### ISSUE TITLE
Will you consider parsing the section field for each body_text?

### ISSUE THREAD

**Issue by tomleung1996** [allenai/s2orc#14]
I notice that most of the `section` field is set to `null`, except the ones in the abstract.

It would be very helpful if this field could be filled in with actual values in future updates.

**Comment by kyleclo** [comment]
Hey @tomleung1996, yes this is a known bug that we're fixing in the next release

**Comment by kyleclo** [comment]
@tomleung1996 It's fixed in our latest release `20200705v1`.  Here's a screenshot of `grep '"section":'` on our `pdf_parses/`
![image](https://user-images.githubusercontent.com/13603748/86875218-d9cdec00-c096-11ea-8224-63901487e183.png)
