### ISSUE TITLE
How to identify the category of each paper

### ISSUE THREAD

**Issue by yingtaomj** [allenai/s2orc#18]
In figure 2 we can see the Distribution of papers by Microsoft Academic field of study. How to identify this category information in the provided dataset?

**Comment by kyleclo** [comment]
@yingtaomj  See the `metadata.csv` files have provided fields of study per paper

**Comment by kyleclo** [comment]
For example, each row looks like

{"paper_id": "77490025", "title": "State...  "year": 1975, **"mag_field_of_study": ["Medicine"]**, ...}
