### ISSUE TITLE
how can I get affilication information of authors

### ISSUE THREAD

**Issue by shizhediao** [allenai/s2orc#22]
Hi,
I was wondering how can I get the affiliation (institution or nationality) of authors
Is it possible?
Thanks!

**Comment by kyleclo** [comment]
Hey @shizhediao, not currently.  I know MAG has pretty good author information, and S2ORC provides `mag_ids` of a large collection of its papers.  I would maybe go the route of trying to join against that metadata to obtain that information.

**Comment by shizhediao** [comment]
OK! I see.
Thanks for your reply!
