### ISSUE TITLE
Different names for the same venue / journal

### ISSUE THREAD

**Issue by ZiningZhu** [allenai/s2orc#26]
Thanks for the hard work collecting these data. I found some publications on the same venues appear to have different venue entries. Do you plan to unify them in the future?

E.g: `EMNLP`, `EMNLP/IJCNLP`, `EMNLP 2011`, `EMNLP 2015`, `Conference On Empirical Methods In Natural Language Processing`, `2007 Joint Conference on Empirical Methods in Natural Language Processing and Computational Natural Language Learning (EMNLP-CoNLL)`

**Comment by kyleclo** [comment]
Hey @ZiningZhu  we don't currently have plans to normalize these into the same entity.  There's someone on the team who's looking into this, but it's very early stage right now so we can't promise when a reasonable solution will make it to a future S2ORC version.
