### ISSUE TITLE
How to extract citation sentences ?

### ISSUE THREAD

**Issue by Soumyajain29** [allenai/s2orc#33]
Hii,
I am working with the dataset. For my research work, I want to extract citation sentences.  
For example, suppose paper A cites paper B. Then there must be a sentence in paper A describing paper B. I want to extract this sentence. I know citation spans are available, which will help in extracting those sentences. But is there any preferred library (NLTK, spacy ) / way that should be used for sentence spitting?
I tried using spacy. But I am unable to extract these sentences properly.

It would be very helpful if an example code snippet can be shared. 

Thanks

**Comment by kyleclo** [comment]
Hi @Soumyajain29, I would recommend checking out https://allenai.github.io/scispacy/ for sentence splitting.

**Comment by Soumyajain29** [comment]
Thanks for the suggestion, Kyle.
