### ISSUE TITLE
Unique authors' identifiers

### ISSUE THREAD

**Issue by AmenRa** [allenai/s2orc#39]
Hi and thanks for the dataset!

Is there any plan to release an updated version of the dataset with unique authors' identifiers?

Right now, building an authorship / co-authorship graph with the available data does, unfortunately, lead to severe noise issues.

As far as I understand, the dataset is somewhat linked to the Semantic Scholar corpus, which should make this doable for you.

Any help on this would be great.

Best,
 
Elias

**Comment by lucylw** [comment]
Hi Elias,

We do not currently have plans to incorporate author IDs into S2ORC. You can use the [Semantic Scholar API](https://www.semanticscholar.org/product/api) to retrieve associated author IDs from Semantic Scholar. 

-Lucy

**Comment by AmenRa** [comment]
Hi Lucy and thanks for your answer.
I will take a look at the API.
